# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RS-p-y8SnmY71umLEsTDiEBbu96jUVzX
"""


import pandas as pd
import requests
from bs4 import BeautifulSoup
Product_name = []
Prices = []
Reviews = []

for i in range(2,22):
    url = "https://www.flipkart.com/search?q=mobiles&as=on&as-show=on&otracker=AS_Query_TrendingAutoSuggest_1_0_na_na_na&otracker1=AS_Query_TrendingAutoSuggest_1_0_na_na_na&as-pos=1&as-type=TRENDING&suggestionId=mobiles&requestId=caf0d6ac-6555-4f11-8a2f-79a290d2f689&page=" + str(i)
    r = requests.get(url)

    soup = BeautifulSoup(r.text, "lxml")
    box = soup.find("div", class_ ="_1YokD2 _3Mn1Gg")

    names = box.find_all("div",class_ = "_4rR01T")
    for i in names:
      name = i.text
      Product_name.append(name)
    print(Product_name)

    prices = box.find_all("div",class_ = "_30jeq3 _1_WHN1")
    for i in prices:
      name = i.text
      Prices.append(name)
    print(Prices)

    reviews = box.find_all("div", class_ ="_3LWZlK")
    for i in reviews:
      name = i.text
      Reviews.append(name)
    print(Reviews)

df = pd.DataFrame({"Product Name":Product_name, "Prices":Prices, "Reviews":Reviews })
#print(df)

df.to_csv("flipkart_mobiles.csv")
